global:
  scrape_interval: 5s  # frecuencia con que se recolectan métricas
  evaluation_interval: 15s

scrape_configs:
  # Prometheus monitoreándose a sí mismo
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Ejemplo de microservicio 1
  - job_name: "nbu-be"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["nbu-be:8080"]
