server:
  http_listen_port: 3200
  grpc_listen_port: 9095    # ðŸ‘ˆ antes estaba 4317, cambiÃ¡lo para no colisionar

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

compactor:
  compaction:
    block_retention: 48h

storage:
  trace:
    backend: local           # ðŸ‘ˆ ESTE CAMPO ES CLAVE
    local:
      path: /tmp/tempo       # ruta dentro del contenedor
    wal:
      path: /tmp/tempo/wal   # Write-Ahead Log